name: Deploy Portfolio

on:
  push:
    branches:
      - main
    paths:
      - 'course-portfolio/**' # Экшен запустится только если изменились файлы в этой папке
  workflow_dispatch: # Оставляем возможность запускать вручную

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
          # Если package.json лежит внутри папки, указываем путь для кэширования
          cache-dependency-path: course-portfolio/package-lock.json

      - name: Install dependencies
        # Переходим в папку перед установкой
        run: cd course-portfolio && npm ci

      - name: Build project
        # Переходим в папку перед сборкой
        run: cd course-portfolio && npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Указываем путь к папке dist внутри вашей папки проекта
          publish_dir: ./course-portfolio/dist
